try to fix travis error
Here's the error:

    * installing *source* package ‘gert’ ...
    ** package ‘gert’ successfully unpacked and MD5 sums checked
    ** using staged installation
    Using PKG_CFLAGS=
    Using PKG_LIBS=-lgit2
    ----------------------------- ANTICONF -------------------------------
    Configuration failed to find libgit2 library. Try installing:
     * brew: libgit2 (MacOS)
     * deb: libgit2-dev (Debian, Ubuntu, etc)
     * rpm: libgit2-devel (Fedora, CentOS, RHEL)
    If libgit2 is already installed, check that 'pkg-config' is in your
    PATH and PKG_CONFIG_PATH contains a libgit2.pc file. If pkg-config
    is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
    R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
    -------------------------- [ERROR MESSAGE] ---------------------------
    <stdin>:1:18: fatal error: git2.h: No such file or directory
    compilation terminated.
    ----------------------------------------------------------------------
    ERROR: configuration failed for package ‘gert’
    * removing ‘/home/travis/R/Library/gert’
    Error in i.p(...) :
      (converted from warning) installation of package ‘gert’ had non-zero exit status
    Calls: <Anonymous> ... with_rprofile_user -> with_envvar -> force -> force -> i.p
    Execution halted
    The command "Rscript -e 'deps <- remotes::dev_package_deps(dependencies = NA);remotes::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'" failed and exited with 1 during .
    Your build has been stopped.